language: python
os: linux
python:
  - "3.6"
  
services:
  - docker

before_install:
  - docker build -t ravestate .
  - docker run -t -v $(pwd):/ravestate -w /ravestate ravestate ./run_tests.sh

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

after_success:
  - codecov
