language: python
os: linux
python:
  - "3.6"

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
  
services: docker

before_install: docker pull realitivity/ravestate:0.7.0

install: pip install codecov

script: docker run -t -v $(pwd):/ravestate -w /ravestate ravestate ./run_tests.sh

after_success: codecov
