# neo4j.yml should contain at least the following yaml document:
#
# module: ontology
# config:
#   neo4j_pw: "your_password"


!include config/neo4j.yml

---
module: core
config:
  import:
    - ravestate_conio
    - ravestate_nlp
    - ravestate_roboyqa
    - ravestate_ontology
