---
module: core
config:
  import:
    - ravestate_telegramio
    - ravestate_conio
    - ravestate_sendpics
    #- ravestate_wildtalk
    #- ravestate_nlp
---
module: telegramio
config:
  all_in_one_context: True